### ISSUE TITLE
styleMap doesn't remove existing styles it previously created - clarify docs

### ISSUE THREAD

**Issue by alindsay55661** [Polymer/lit-html#1108] opened 2020-03-04 21:33 UTC
# Description

Current docs for `styleMap` state that it must be the only binding, but the binding behavior is not completely obvious. I initially interpreted this to mean `styleMap` can be used to add _and remove_ styles if they were previously added through the binding (i.e. non-static). However, `styleMap` cannot remove styles it previously added. This should be clarified in the docs.

**Comment by arthurevans** [comment] 2020-03-17 17:50
I'm not sure I understand. You have a binding like `style=${styleMap(styleObj)}` and it's not removing styles when you update the object?

Are you doing something like this? https://codesandbox.io/s/lit-html-starter-x72v4

**Comment by justinfagnani** [comment] 2020-03-17 18:26
Yeah, this sounds like a bug report, not a docs issue, as `styleMap` should definitely be removing previously added styles. But like Arthur's demo, we're not aware of this not working. Please add a reproduction we can try out.

**Comment by sorvell** [comment] 2020-03-26 18:41
Closing since more info was not provided. Please feel free to open a new issue with a reproduction of the issue, if it's still a problem.

**Closed by sorvell** 2020-03-26 18:41 UTC
Labels: More Info Needed
