### ISSUE TITLE
Duplicate property on element causes subsequent interpolation to not render

### ISSUE THREAD

**Issue by ernsheong** [Polymer/lit-html#403] opened 2018-07-16 01:37 UTC
```js
_render({ inputSchema, disabled }) {
    return html`
      ${style}
      ${repeat(
        inputSchema.rows || [],
        input => input.id || console.error("Missing id"),
        input => {
          return html`
            ${"TEST BEFORE" || ""}
            <kr-input
              id$=${input.id}
              disabled=${disabled} 
              ...
              disabled=${input.disabled} // DUPLICATE
            ></kr-input>
            ${"TEST AFTER" || ""}
          `;
        }
      )}
    `;
  }
}
```

Expectation: TEST AFTER is rendered (or throw error)
Actual: TEST AFTER is not rendered

Very odd.

**Comment by bgotink** [comment] 2018-07-16 20:06
This makes sense, lit-html uses the browser's parser and that parser ignores duplicate attributes:

```js
const div = document.createElement('div');
div.innerHTML = `<div foo=1 foo=2></div>`

console.log(div.innerHTML);
// prints: <div foo="1"></div>
```

The missing attribute when walking the tree means lit-html is off by one when matching the parameters passed in the template to the location in the DOM to put them in. [Here](https://next.plnkr.co/edit/cbIYXpTAwdlzluIy?open=lib%2Fscript.js) is a small reproduction that shows the off-by-one error due to the duplicate attribute.

**Comment by justinfagnani** [comment] 2018-07-16 20:16
This might be very tricky to fix. We only know how many attributes to associate with expressions from the parsed DOM. I'm not sure how we could tell that an expression belongs to one element and but the next.

I can't see how to disambiguate this case:

```js
html`<div id=${i} id=${i}></div><div id=${i}></div>
```

**Comment by bgotink** [comment] 2018-07-16 20:42
I think the simplest solution is probably to verify after parsing the template that the number of parameters in the string matches the number of parts we've found (I'm thinking in terms of #400 where an `AttributePart` has a single value).

**Comment by ruphin** [comment] 2018-08-05 23:34
Testing if the number of parts is correct will not be able to detect this case of double attribute assignment:

```javascript
html`<div id=${i} id="dup"></div>`
```

The question is if this is our responsibility. As long as rendering does not break because values are assigned to incorrect parts, I think it is fine.

**Comment by justinfagnani** [comment] 2018-08-24 07:07
The current solution we're going to with is to use linters like eslint-plugin-lit, which already has a rule for this. There are a lot of other ways to break templates that we can't detect or recover from. Going to close this now as mostly unfeasible.

**Closed by justinfagnani** 2018-08-24 07:07 UTC
Labels: Priority: Medium, Status: Available, Type: Enhancement
