### ISSUE TITLE
Unexpected token error in tests

### ISSUE THREAD

**Issue by stefanfrede** [Polymer/lit-html#482] opened 2018-09-09 10:33 UTC
I don't know if this is `lit-html` related or not, but if I try to test something where `lit-html` is involved I get an unexpected token error:
```js
/Users/foo/bar/baz/node_modules/lit-html/lit-html.js:14
import { defaultTemplateProcessor } from './lib/default-template-processor.js';
       ^
```
This happened with Mocha and Jest.

**Comment by web-padawan** [comment] 2018-09-09 10:55
Which testing tool are you using? In case of `karma-webpack`, you would have to configure `babel-loader` to process node_modules e.g. like this:
```js
    {
      test: /\.js$/,
      loader: 'babel-loader',
      exclude: /node_modules\/(?!(@webcomponents\/shadycss|lit-html|@polymer|)\/).*/,
      options: {
        cacheDirectory: true
      }
    }
```
Working example: https://github.com/web-padawan/lit-components/blob/d995536f5bf94f7c496937fafc60bb7aa63d698a/utils/webpack.common.js#L6

**Comment by stefanfrede** [comment] 2018-09-09 11:49
At the moment I just use `lit-html` without any extras (no Polymer, web components, etc.) and Mocha as my testing environment.

This is my playground: https://github.com/stefanfrede/knowthen-counter/tree/write-tests.

If I import [counter.js](https://github.com/stefanfrede/knowthen-counter/blob/write-tests/src/counter.js) in [counter.test.js](https://github.com/stefanfrede/knowthen-counter/blob/write-tests/tests/counter.test.js) I get the unexpected token error because of the `lit-html` import in [view.js](https://github.com/stefanfrede/knowthen-counter/blob/write-tests/src/view.js).

I run my tests without webpack: `mocha --require @babel/register tests/**/*.test.js`.

**Comment by LarsDenBakker** [comment] 2018-09-09 11:53
Running plain mocha executes the test in node js, I think. Node doesn't natively support es modules yet, so you will need to compile those before running the tests. Lit-html requires a browser environment to work though, so it will fail on other errors as well.

**Comment by stefanfrede** [comment] 2018-09-09 12:15
As far as I understand it the `--require @babel/register` part does the trick for Mocha regarding modules and other new goodnesses.

I currently try to write tests for my [actions](https://github.com/stefanfrede/knowthen-counter/blob/write-tests/src/actions.js) where Crocks gets imported and there I have no problems at all.

Besides that Mocha runs in webpack  when you start the test watcher in my repo (`npm run test:watch`) and there I run into the same problem.

**Comment by justinfagnani** [comment] 2018-09-17 22:08
@stefanfrede I notice that the branch you linked to is deleted and you currently have tests in master. Is this still a problem? lit-html requires that your environment support modules or that you compile modules out. We generally use browser-based testing, because lit-html uses DOM APIs, so I'm unfamiliar with how to configure node in this scenario (outside of using the `esm` in a few projects).

**Comment by keanulee** [comment] 2018-10-23 23:01
I doubt lit-html will run as-is in Node.js given that it uses ES modules and isn't `.mjs`. As @web-padawan suggested, you can modify webpack config to include `node_modules/lit-html` (i.e. [here](https://github.com/stefanfrede/knowthen-counter/blob/lit-html-test-error/webpack.config.js#L40)) to make sure babel can transpile those `import` statements. Not sure how lit-html would behave beyond that though.

**Comment by justinfagnani** [comment] 2018-11-21 19:41
Closing since we don't directly support running in Node, and definitely require either an environment that supports modules, or a toolchain to compile modules out.

**Closed by justinfagnani** 2018-11-21 19:41 UTC

**Comment by justinfagnani** [comment] 2019-01-23 19:53
I think in this case we're more like a generation ahead than a generation behind. We write for modern browsers, all of which support modules. Older browsers and Node will require a build/bunding step.

jsdom doesn't support modules either, so it needs to catch up, but it also doesn't support Custom Elements, so in many cases even that won't be enough. Puppeteer with Headless Chrome is probably a better choice for fast, command-line-only tests.

**Comment by leegee** [comment] 2019-01-23 20:22
Indeed — and that's the problem!

Cheers
Lee

**Comment by alber70g** [comment] 2019-02-14 12:09
I'm using jest and running the tests won't run and give the same error as OP. What's the solution to do this? I'm using ts-jest and my tests are in ts as well.

**Comment by justinfagnani** [comment] 2019-02-14 16:38
lit-html is distributed as standard JS modules. Node doesn't support modules yet. If you're trying to load the lit-html source into Node you'll have to compile to CommonJS presumably.

**Comment by djforth** [comment] 2019-04-06 13:17
I'm having the same issue. Does anyone know  a work around for jest? I've tried everything to make it work with no joy.

**Comment by justinfagnani** [comment] 2019-04-06 19:41
@djforth it really seems like Jest and jsdom need some modernization. I'd try Puppeteer. That way you'd be running tests in a real browser that you support. IOW - do you support Jest as a browser for your users?

**Comment by djforth** [comment] 2019-04-08 13:32
@justinfagnani while I take your point, I was using karma and jasmine before moving to jest and the test suite was slow and tended to heap out of memory often. I'd also add that I haven't had any issues moving to jest in terms of testing in real browser, so the convenience of a more stable test suite without re-writing to another test framework is unfortunately preferable in my team.

I guess the issue is that jsdom(and jest) is node based and think there is few issues with this node and es6 modules, although I'm not sure why I can't get babel to transpile it. I think you can get Jest to work with puppeteer, but not sure how easy it is to implement, might have a look when I have time.

TBH I think lit-html might be overkill for what I'm doing so might stick to standard template strings to save the hassles. But this looks like an interesting project so hopefully node get modules or some figures out a work around, so can take a look in future.

**Comment by djforth** [comment] 2019-04-09 12:20
Ah ha, I figured out a solution for the jest issue.  In your jest config add the following

`  "transformIgnorePatterns": ["/node_modules/(?!lit-html).+\\.js"],`

This is important, re-name your babel config to babel.config.js (mine was .babelrc.js)

See here for the fix - https://github.com/facebook/jest/issues/6229#issuecomment-403539460

Hopefully that will help people!

**Comment by FaBeyyy** [comment] 2019-04-11 13:10
> Ah ha, I figured out a solution for the jest issue. In your jest config add the following
> 
> ` "transformIgnorePatterns": ["/node_modules/(?!lit-html).+\\.js"],`
> 
> This is important, re-name your babel config to babel.config.js (mine was .babelrc.js)
> 
> See here for the fix - [facebook/jest#6229 (comment)](https://github.com/facebook/jest/issues/6229#issuecomment-403539460)
> 
> Hopefully that will help people!

Hey there, i did exactly the same but cannot get it working...still getting this error
```
import { defaultTemplateProcessor } from './lib/default-template-processor.js';
SyntaxError: Unexpected token {
```
babel.config.js
```js
module.exports = {
    "presets": [
        "@babel/preset-typescript",
        "@babel/preset-env",
    ],
}
```
jest.config.js
```js
module.exports = {
  "transformIgnorePatterns": ["/node_modules/(?!lit-html).+\\.js"],
  "preset": "ts-jest"
}
```

Appreciate your help!

**Comment by djforth** [comment] 2019-04-11 13:51
Apologies @FaBeyyy I don't use TypeScript, it looks to me like something within the typescript/ts-jest config.  Looking at the thread maybe a custom transform might help? - https://github.com/facebook/jest/issues/6229#issuecomment-449945502

**Comment by tamj0rd2** [comment] 2020-06-12 17:01
I'm not using ts-jest and I still have this issue

**Comment by justinfagnani** [comment] 2020-06-12 17:30
@tamj0rd2 lit-html is distributed as standard JS modules. You need to load them in an environment that supports JS modules, or transpile your application, including dependencies, to whatever module system your environment supports.
