### ISSUE TITLE
how to construct variable tag (element) name

### ISSUE THREAD

**Issue by mustafaekim** [Polymer/lit-html#371] opened 2018-06-17 09:13 UTC
Hi, in my first web component, I wanted to simply create a component which takes an element name through some attribute and then create a tag of it. So I've written the template as below

```ts
    _render({ element_name }) {
        return html`
                    <style>
                        :host {
                            display: block;
                        }
                    </style>
                    
                    <${element_name}>some content</${element_name}>
                    
        `
    }
```

That does not work. I was thinking like whatever inside the ${} will be outputted but it doesnt. Instead somehow it is converted into escaped strings. How can I achieve my goal?

(as fas as I understand there are only **a few** places where  I can use ${}. What are the rules here? How to escape the rules?)

**Comment by TimvdLippe** [comment] 2018-06-17 22:07
This is a duplicate of #78.

**Closed by TimvdLippe** 2018-06-17 22:07 UTC
