### ISSUE TITLE
[labs/task] Investigate task ergonomics

### ISSUE THREAD

**Issue by taylor-vann** [Polymer/lit-html#3005] opened 2022-06-07 17:14 UTC
## Description

Tasks are a way to execute and visualize asynchronous operations inside a LitElement.

The dx behind chaining tasks and canceling tasks isn't well defined. Create examples that cover different use cases:
- initial values
- placeholder render
- cancelling tasks

## Acceptance criteria

This issue can be closed when examples can help decide whether a use case can be expressed through a composition pattern or if an update to the Task API is necessary.

**Comment by rictic** [comment] 2023-07-06 17:40
Dupe of https://github.com/lit/lit/issues/1499

**Closed as completed by rictic** 2023-07-06 17:40 UTC
