### ISSUE TITLE
Error throw when re-rendering text nodes.

### ISSUE THREAD

**Issue by ebidel** [Polymer/lit-html#318] opened 2018-05-08 16:27 UTC
I have a template that looks like this (uses text nodes):

```js
 const tmpl = html`
    <label>LH</label>: ${numLHRuns},
    <label>PSI</label>: ${numPSIRuns},
    <label>WPT</label>: ${numWPTRuns}
  `;

  render(tmpl, container);
```

When I call this code again and render it another time lit throws an error. Apologies for not having the stack trace handy. I neglected to file this a few days ago and the code is already changed.

**Comment by justinfagnani** [comment] 2018-05-20 19:47
I don't see any reason why this should throw, and this is the basic form of bindings we have in test. Was this fixed at I/O? Any way we could reproduce?

**Comment by paulcodiny** [comment] 2018-06-27 13:37
I'm not sure this is the same issue, but I encountered the similar problem:
```
lion-lit.js:554 Uncaught TypeError: Cannot read property 'nodeType' of null
    at NodePart._setText (lion-lit.js:554)
    at NodePart.setValue (lion-lit.js:519)
    at TemplateInstance.update (lion-lit.js:687)
    at Object.render$1 [as renderShady] (lion-lit.js:1237)
    at HTMLElement.__renderingShadowDom (LionLitRenderMixin.html:21)
    at HTMLElement.__processRendering (LionElement.html:232)
    at HTMLElement._render (LionElement.html:189)
    at HTMLElement.update (LionElement.html:105)
    at HTMLElement.set isAlertOpened [as isAlertOpened] (ing-web-page-login.html:46)
    at HTMLElement._setPendingPropertyOrPath (property-effects.html:1559)
```

`lion-lit.js` is a LitHTML bundled with bower support 
LitHTML is the latest master

`TemplateInstance.update` has as argument the following `values`:
```
[{"strings":["\n      <style></style>\n    "],"values":[],"type":"html"},false,null,"New in My ING: IBAN name check","Avoid incorrect transfers? <a href=\"https://www.ing.nl/particulier/betalen/betalingen-doen/ibannaamcheck/index.html\">Find out how (in Dutch)</a>","Log in to My ING",null,"Personal","Business",null,"User name","Password",null,"Remember my User name",null,"Login","Need help?","Secure Banking","Privacy and cookies","Disclaimer"]
```

and the `valueIndex` when breaks is `4`

Unfortunately, I can't make the smallest reproducible code, but even with this error everything seems working. But if I change the code:
```
// NodePart._insert
this.endNode && this.endNode.parentNode && this.endNode.parentNode.insertBefore(node, this.endNode);
// instead of this.endNode.parentNode.insertBefore(node, this.endNode);

// NodePart._setText
...
if (node &&
  node === this.endNode.previousSibling &&
  node.nodeType === Node.TEXT_NODE) {
/* instead of if (node === this.endNode.previousSibling &&
  node.nodeType === Node.TEXT_NODE) { */

// removeNodes
while (node && node !== endNode) {
// instead of while (node !== endNode) {
```
then error disappears, but I don't understand the consiquences of these changes

**Comment by tpluscode** [comment] 2018-07-11 18:23
I've been seeing the same error recently with 0.10.2. I too have been unable come up with a minimal repo but I did some debugging and I found that the second time the template is being processed `NodePart#startNode` and `NodePart#endNode` have all their siblings null. I have no clue as to when and why these siblings get removed

**Comment by justinfagnani** [comment] 2018-08-29 20:03
Move to low priority until we have a reproduction.

**Comment by SnareChops** [comment] 2019-01-07 22:57
@justinfagnani Encountering this same issue when working with `<textarea>`. Created a minimal reproduction at https://github.com/SnareChops/lit-bug-repro. Details in the reproductions repo.

**Comment by justinfagnani** [comment] 2019-01-07 23:06
@SnareChops could you make an online repro, maybe in StackBlitz? What part of the repo is relevant? There's a lot of code there besides the `<textarea>`.

Also, I see a bug in the template around the `<textarea>`:

```
    <textarea placeholder=${e.placeholder || e.label} rows=${e.rows} @input=${e.change.bind(e)}>${e.value || ''}</textarea>
```

There's a missing greater-than bracket to close out the opening `textarea` tag. If you add that back does the problem go away?

**Comment by justinfagnani** [comment] 2021-04-15 20:44
Closing since we don't have a reproduction. We also allow unquoted bindings at the end of the tag in 2.0, which might help. Feel free to reopen if this is still an issue.

**Closed by justinfagnani** 2021-04-15 20:44 UTC
Labels: Severity: Low, Type: Bug
