### ISSUE TITLE
Repeat derective dont work

### ISSUE THREAD

**Issue by bulletbrand** [Polymer/lit-html#1431] opened 2020-11-13 00:17 UTC
Guys I get the following error when I try to use repeat derective to fix select
npm dupl didn't help, as well as reinstalling nodemodules what could be the problem?

if (!(containerPart instanceof lit_html_js__WEBPACK_IMPORTED_MODULE_0_["NodePart"])) { throw new Error('repeat can only be used in text bindings'); } // Old part & key lists are retrieved from the last update (associated // with the part for this instance of the directive) const oldParts = partListCache.get(containerPart) || []; const oldKeys = keyListCache.get(containerPart) || []; // New part list will be built up as we go (either reused from old parts // or created for new keys in this update). This is saved in the above // cache at the end of the update. const newParts = []; // New value list is eagerly generated from items along with a parallel // array indicating its key. const newValues = []; const newKeys = []; let index = 0; for (const item of items) { newKeys[index] = keyFn ? keyFn(item, index) : index; newValues[index] = template(item, index); index++; } // Maps from key to index ..................

**Comment by kevinpschaaf** [comment] 2020-11-13 20:14
This is likely due to multiple versions of `lit-html` being installed in `node_modules` in your project; you need to ensure that the `repeat` directive is being loaded from the same `lit-html` package as `render`/`html` that is being used.  

Please try running `npm dedupe` on your project, which should help ensure that only one version of `lit-html` exists.  Note this is good practice either way, since loading multiple compatible versions impacts your payload also.

The issue is covered in https://github.com/Polymer/lit-html/issues/1195. Despite being bad for performance, the upcoming 2.0 release of lit-html allow for multiple compatible versions of lit-html to be used on the same page.

**Comment by bulletbrand** [comment] 2020-11-16 08:54
npm depub command didn't solve the problem, maybe there is some problem in my package.json?
{
  "name": "app",
  "version": "1.0.0",
  "author": "name",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0",
    "@granite-elements/granite-spinner": "^3.0.0",
    "@polymer/lit-element": "^0.6.4",
    "@vaadin/router": "^1.1.0",
    "@vaadin/vaadin-accordion": "^1.2.0",
    "@vaadin/vaadin-button": "^2.4.0",
    "@vaadin/vaadin-checkbox": "^2.5.0",
    "@vaadin/vaadin-combo-box": "^5.4.1",
    "@vaadin/vaadin-form-layout": "^2.3.0",
    "@vaadin/vaadin-notification": "^1.6.0",
    "@vaadin/vaadin-progress-bar": "^1.3.0",
    "@vaadin/vaadin-radio-button": "^1.5.1",
    "@vaadin/vaadin-select": "^2.4.0",
    "@vaadin/vaadin-tabs": "^3.2.0",
    "@vaadin/vaadin-text-field": "^2.8.1",
    "@webcomponents/webcomponentsjs": "^2.2.1",
    "bcrypt": "^5.0.0",
    "express": "^4.16.3",
    "knex": "^0.21.6",
    "lit-html": "^0.14.0",
    "mysql": "^2.18.1",
    "nanoid": "^3.1.12",
    "node-fetch": "^2.6.1",
    "nodemailer": "^6.4.11",
    "promise-polyfill": "^8.0.0",
    "pwa-helpers": "^0.8.4",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "whatwg-fetch": "^2.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.1.0",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-proposal-decorators": "^7.1.2",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "babel-loader": "^8.0.2",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "css-to-string-loader": "^0.1.3",
    "eslint": "^4.19.1",
    "eslint-plugin-import": "^2.13.0",
    "html-webpack-plugin": "^4.0.0-alpha",
    "polymer-cli": "^1.8.0",
    "postcss-cssnext": "^3.1.0",
    "postcss-loader": "^3.0.0",
    "postcss-preset-env": "^6.0.6",
    "wct-browser-legacy": "^1.0.1",
    "webpack": "^4.19.1",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.4",
    "webpack-merge": "^4.1.3"
  },
  "scripts": {
    "build": "webpack --env production",
    "lint": "eslint ./src/*.js",
    "postinstall": "npm run build",
    "start": "node app.js | webpack-dev-server --env development",
    "test": "polymer test --local chrome --npm",
    "transfer": "rsync -avz . $npm_config_deploy_path",
    "deploy": "npm run build && npm run transfer"
  }
}

**Comment by kevinpschaaf** [comment] 2020-11-19 19:54
Yeah, so it looks like you're pulling in some really old, pre-release versions of `lit-html` and `lit-element`, which are likely resulting in non-deduplicatable versions of lit-html.

Can you try this?

```
npm uninstall lit-html @polymer/lit-element
npm install lit-html lit-element
npm dedupe
```

**Comment by kevinpschaaf** [comment] 2020-12-03 20:24
Did updating your versions fix your issue here? If so we'll go ahead and close the issue. Thanks.

**Closed** 2021-04-15 21:13 UTC
Labels: More Info Needed
