### ISSUE TITLE
Dynamic tags: Impossible?

### ISSUE THREAD

**Issue by raphaellueckl** [Polymer/lit-html#1054] opened 2020-01-09 15:05 UTC
Can anyone tell me why I cannot use variables within lit-html's html method?

```
const h1 = 'h1';
return html`
  <${h1} class="a-heading ${classes}">
    <slot></slot>
  </${h1}>
`;
```

If I replace `${h1}` with `h1` that works without problems.

**Comment by abraham** [comment] 2020-01-09 15:55
Related: https://github.com/Polymer/lit-html/issues/78

**Comment by justinfagnani** [comment] 2020-01-09 17:04
Yeah, this is a dupe of #78 

Until we can do static bindings safely by relying on spec-compliant template literal implementations (which should be after we stop supporting classic Edge) we can't really support this. The performance cost is too much.

**Closed by justinfagnani** 2020-01-09 17:04 UTC

**Comment by mzeiher** [comment] 2020-01-10 08:54
I had the same issues so I prototyped a helper lib: https://github.com/mzeiher/lit-html-scoped-registry-helper
I mainly needed a way to work with a scoped custom element registry (thus the custom templateFactory) but I also created a html`` replacement for that case (currently only tested on FF, Chrome and Safari)
