### ISSUE TITLE
Multiple bindings in class attribute breaks on shady render

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/lit-html#597] opened 2018-10-30 15:24 UTC
We're seeing that when using shady render, placing multiple bindings in a class attribute throws off shady render. But this only happens when it is followed by another attribute, and there is a space in-between the two bindings in the class.

When I render:
```
<div class="${true} ${true}" bar="${true}"></div>
```
it breaks. but any of these work fine:

```
<div class="${true} ${true}"></div>
<div class="${true}" bar="${true}"></div>
<div class="${true}${true}" bar="${true}"></div>
```

It also breaks on chrome with shady dom forced. It only breaks on the class attribute. It fails on this check: https://github.com/Polymer/lit-html/blob/master/src/lib/template.ts#L88

I know using two bindings in one attribute is tricky, so I'd be fine if we say this is not supported by lit-html. But then we need to make sure there is a more descriptive error, and that it's documented.

Sorry I couldn't get a jsbin working at the moment, our proxy at work blocks it.

**Comment by justinfagnani** [comment] 2018-11-12 16:20
Thanks for the report. It sounds like this has to do with the scoping that ShadyCSS does. @sorvell or @azakus could you take a look?

**Comment by sorvell** [comment] 2018-11-29 23:43
I'm in the process of adding a test for this using the given example and was unable to reproduce the issue with the latest `lit-html` release.

Has the issue been resolved? And if not, would you mind making a reproduction.

**Comment by mzeiher** [comment] 2019-02-02 13:03
updating to @webcomponents/webcomponentsjs 2.2.6 fixed classMap issue in IE11 -> so it was a shadycss/shadydom issue

**Comment by kevinpschaaf** [comment] 2019-05-24 18:16
Closing, as the issue appears to be resolved.

**Closed by kevinpschaaf** 2019-05-24 18:16 UTC
Labels: Priority: High, Status: Available, Type: Bug
