### ISSUE TITLE
how to rerender the content without cache

### ISSUE THREAD

**Issue by chenxiaoleizi** [Polymer/lit-html#1169] opened 2020-05-20 09:10 UTC
When the template rendered, use jQuery to change the dom style, then render the template with other data,but the last changed style is still there, so how to rerender the template without cache?
Here is the link [demo](https://codesandbox.io/s/reverent-snowflake-3usqp?file=/src/styles.css)

**Comment by csvn** [comment] 2020-05-20 12:03
This is by design, and one of the reasons that `lit-html` is performant and small. Only the expressions in `${}` are updated between renders of a specific template. From the docs:

> When the result is rendered, lit-html only updates the expressions whose values have changed since the previous render.
> https://lit-html.polymer-project.org/guide/concepts#thinking-functionally

My suggestions would be:

1. Embed `html` templates inside functions that can re-render the template. This makes it easier to render different states
2. Use state, either as paramaters or just in lexical scope, to change how content is rendered
3. Nest `html` templates instead of querying for elements to render into. This can help avoid bugs if we change classes/layout and we forget to change the selector.
4. Use `styleMap` to set the color, and make sure the styles depend on some state we can change

```js
let app = document.getElementById("app");
let users = [{ name: "1" }, { name: "2" }, { name: "3" }];

/*1*/
function renderContent(user, color /* 2 */) {
  render(html`
    <div class="btns">
      ${users.map(user => html`
        <span class="tab" @click=${() => renderContent(user, null)}>
          ${user.name}
        </span>
      `)}
    </div>
    <div class="content">
      ${ /* 3 */ user ? html`
        <div>
          <p style=${ /* 4 */ styleMap({ color })}>${user.name}</p>
          <button @click=${() => renderContent(user, "orange")}>
            change color
          </button>
        </div>
      ` : ""}
    </div>`,
    app
  );
}

renderContent();
```
https://codesandbox.io/s/gracious-hopper-79hte

In addition to making sure we render the correct state, jQuery is not required with the changes above. Of course, it's possible to extract the nested `html` template into it's own function as well. Another alternative is to use [`LitElement`}(https://lit-element.polymer-project.org/) to make it easier to use state in components.

**Comment by chenxiaoleizi** [comment] 2020-05-21 01:05
> 
> 
> This is by design, and one of the reasons that `lit-html` is performant and small. Only the expressions in `${}` are updated between renders of a specific template. From the docs:
> 
> > When the result is rendered, lit-html only updates the expressions whose values have changed since the previous render.
> > https://lit-html.polymer-project.org/guide/concepts#thinking-functionally
> 
> My suggestions would be:
> 
>     1. Embed `html` templates inside functions that can re-render the template. This makes it easier to render different states
> 
>     2. Use state, either as paramaters or just in lexical scope, to change how content is rendered
> 
>     3. Nest `html` templates instead of querying for elements to render into. This can help avoid bugs if we change classes/layout and we forget to change the selector.
> 
>     4. Use `styleMap` to set the color, and make sure the styles depend on some state we can change
> 
> 
> ```js
> let app = document.getElementById("app");
> let users = [{ name: "1" }, { name: "2" }, { name: "3" }];
> 
> /*1*/
> function renderContent(user, color /* 2 */) {
>   render(html`
>     <div class="btns">
>       ${users.map(user => html`
>         <span class="tab" @click=${() => renderContent(user, null)}>
>           ${user.name}
>         </span>
>       `)}
>     </div>
>     <div class="content">
>       ${ /* 3 */ user ? html`
>         <div>
>           <p style=${ /* 4 */ styleMap({ color })}>${user.name}</p>
>           <button @click=${() => renderContent(user, "orange")}>
>             change color
>           </button>
>         </div>
>       ` : ""}
>     </div>`,
>     app
>   );
> }
> 
> renderContent();
> ```
> 
> https://codesandbox.io/s/gracious-hopper-79hte
> 
> In addition to making sure we render the correct state, jQuery is not required with the changes above. Of course, it's possible to extract the nested `html` template into it's own function as well. Another alternative is to use [`LitElement`}(https://lit-element.polymer-project.org/) to make it easier to use state in components.

Thanks! I will try your suggestions.

**Comment by justinfagnani** [comment] 2020-05-21 03:01
@chenxiaoleizi is there another reason why you're using jQuery here - like you need to use some existing library code?

Because like @csvn said, lit-html doesn't update any parts of template outside of the expressions. The right way to create dynamic content is to put the dynamic parts into the template and re-render. @csvn's example is good.

**Comment by chenxiaoleizi** [comment] 2020-05-21 06:30
@justinfagnani I was want to find a light template easy to separate code and add event, use JQuery to update the content and style.  But now i think that is the wrong way to use lit-html. As you said i should update parts by rerender. I think it works looks like React, right?

**Comment by kevinpschaaf** [comment] 2020-05-21 18:10
> I think it works looks like React, right?

Yes, lit-html is similar to React in this sense, in that it will update the DOM based on the previous state that _lit_ rendered (not diffing against the last state of the DOM).

It looks like you've got enough information to move forward, so we'll go ahead and close this issue. Please open a new issue if any new questions arise.  Thanks!

**Closed by kevinpschaaf** 2020-05-21 18:10 UTC
