### ISSUE TITLE
IE11/Edge: Lit Markers within SVG causes errors

### ISSUE THREAD

**Issue by deepsnitk** [Polymer/lit-html#594] opened 2018-10-29 03:56 UTC
### Description
When using the 'svg' tagged template of lit-element, if the content within it has a 'path' element for which the 'd' attribute is dynamically set, then the 'd' attribute will be missing in IE11/Edge16 with an error: SVG4601: SVG Path data has incorrect format and could not be completely parsed.
Since 'd' determines the path, there is nothing displayed.

#### Live Demo
https://astonishing-purpose.glitch.me/

#### Steps to Reproduce
Inside 'svg' tagged template literal add 2 elements:
1. An SVG with only static values.
2. Another SVG same as above but with the nested 'path' element having dynamic 'd' value.

#### Expected Results
Output should render 2 SVG elements.

#### Actual Results
Chrome: Both SVGs are visible as expected.
IE11/Edge16: Only one SVG is rendered onto the browser.

### Browsers Affected

- [x] IE 11
- [x] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] Safari 11
- [ ] Safari 10

### Versions
- lit-element: v0.6.1
- webcomponents: v2.1.3

**Comment by mariusGundersen** [comment] 2018-10-29 12:11
OK, I've debugged this in Edge, and found that the problem is in the `TemplateResult.getTemplateElement()` method

```js
    getTemplateElement() {
      const template = document.createElement('template');
      template.innerHTML = this.getHTML();
      return template;
    }
```

the innerHTML of the template is set to 

```html
<svg xmlns="http://www.w3.org/2000/svg"><svg id="pie" viewBox="0 0 100 100" width="100" height="100">
                        <g transform="translate(50 50)">
                            <g class="slice" @click="{{lit-20079031980408946}}" name="{{lit-20079031980408946}}">
                                <path class="slice extended" fill="{{lit-20079031980408946}}" d="M 2.87792e-015 -47 A 47 47 0 0 1 37.5068 28.3238 L 0 0 Z" />
                            </g>
                        </g>
                    </svg><svg id="pie" viewBox="0 0 100 100" width="100" height="100">
                        <g transform="translate(50 50)">
                            <g class="slice" @click="{{lit-20079031980408946}}" name="{{lit-20079031980408946}}">
                                <path class="slice extended" fill="{{lit-20079031980408946}}" d="" />
                            </g>
                        </g>
                    </svg></svg>
```

Two problems here: 
* The `fill` and `d` attributes swap places
* The `d` attribute is empty

This is because Edge refuses to put the `marker` value into this attribute because it's not properly formatted. Instead it produces this error in the console:

```
SVG4601: SVG Path data has incorrect format and could not be completely parsed.
```

**Comment by mariusGundersen** [comment] 2018-10-29 12:29
Can this be solved by not putting the marker in the attribute directly, but replacing the attribute name in the generated html with something like `lit-${name}`, so that instead of containing `<path d="{{lit-1234}}" />` it contains `<path lit-d="{{lit-1234}}" />`? This can be handled in `TemplateInstance._clone()`.

**Comment by mariusGundersen** [comment] 2018-10-29 15:36
There seems to be a workaround for [style attributes in the code](https://github.com/Polymer/lit-html/blob/master/src/lib/template-result.ts#L61). The hacky solution would be to handle the d attribute in a similar way, but there might be more such scenarios to handle. Instead of trying to create an html string with a marker inside each attribute we could add a new marker attribute with a list of attributes that should have parts? Then in the template we don't have to use getAttribute and handle upper/lower case attribute names, we can instead look at one attribute on the element and get a list of all the attributes that needs parts.

**Comment by deepsnitk** [comment] 2018-10-30 06:11
Referencing: [Lit Markers within SVG causes errors](https://github.com/Polymer/lit-element/issues/250)

**Comment by deepsnitk** [comment] 2018-11-07 05:55
@mariusGundersen did you see any elegant solution for this?

**Comment by deepsnitk** [comment] 2018-11-07 05:57
@mariusGundersen did you see any elegant solution for this?

**Comment by justinfagnani** [comment] 2018-11-19 21:51
I have a tentative fix for this incoming.

**Closed** 2018-11-28 19:50 UTC
Labels: Browser: Edge, Browser: IE, Priority: High, Status: Accepted, Type: Bug
