### ISSUE TITLE
Reverse order of first two parameters of render function

### ISSUE THREAD

**Issue by aaronshaf** [Polymer/lit-html#428] opened 2018-08-09 00:56 UTC
Can first parameter of [`render`](https://github.com/Polymer/lit-html/blob/master/src/core.ts#L166) be `container`? This would help with currying. I am more likely to know the render target first.

**Comment by aaronshaf** [comment] 2018-08-09 00:59
This would also make it more compatible with [yo-yo](https://github.com/maxogden/yo-yo). Context: I am trying to make a component lib that can use either yo-yo or lit.

**Comment by justinfagnani** [comment] 2018-08-23 18:48
Dupe of #351, which is also closed.

The current ordering is consistent with React and Reactalikes, and reads (to me, of course) like "render this template to this container".

Note, you can in effect do currying with:

```js
const myRender = (template) => render(template, container);
```

**Closed by justinfagnani** 2018-08-23 18:48 UTC
Labels: Priority: Low, Status: Completed, Type: Enhancement
