### ISSUE TITLE
Proposal: allow server side rendered templates

### ISSUE THREAD

**Issue by frank-dspeed** [Polymer/lit-html#1053] opened 2020-01-05 17:30 UTC
To allow server side rendered templates we need to be able to create a template result from existing template tags.

**Comment by frank-dspeed** [comment] 2020-01-16 05:38
Conclusion is that i will go with my own templating engine based on tagged template strings and maybe use lit-html if i want to use the live bindings it produces with customElements only if needed. 

Why i come to that conclusion?
- would need isomorphic directives while there is no need for directives at all in a string only case.
- Its much more clean and performant to render only strings and apply hooks via customElements that get registered for the rendered string template.

**Comment by justinfagnani** [comment] 2020-01-23 23:45
Duplicate of #187

**Closed by justinfagnani** 2020-01-23 23:45 UTC
