### ISSUE TITLE
classMap can not be used on a slot tag

### ISSUE THREAD

**Issue by zzzgit** [Polymer/lit-html#999] opened 2019-09-03 02:12 UTC
```js
const computedClass = CSSMap({foo: true})

render(){
  return html`<slot class=${computedClass}></slot>`
}
```

and then I got: 

> The `classMap` directive must be used in the `class` attribute and must be the only part in the attribute.

**Comment by justinfagnani** [comment] 2020-01-23 00:36
Do you have a reproduction? I can't think of why this wouldn't work with native shadow DOM, but I can see that it definitely wouldn't work with Shady DOM.

**Comment by justinfagnani** [comment] 2020-10-13 17:44
Closing since this is so old. Please one a new issue if it's still a problem and we have a reproduction.

**Closed by justinfagnani** 2020-10-13 17:44 UTC
Labels: More Info Needed
