### ISSUE TITLE
?checked incorrectly throws Boolean attributes can only contain a single expression error

### ISSUE THREAD

**Issue by robhicks** [Polymer/lit-html#802] opened 2019-02-09 16:53 UTC
# Description
Even when a single boolean express is passed to ?checked it throws the Boolean attributes can only contain a single expression error

# Steps to Reproduce
```JavaScript
const difficulty = ['ADVANCED];
return html`
<input type="checkbox" ?checked=${difficulty.includes('BEGINNING')}/>
`;
```

## Actual Results
```console
idx-project-finder.js:2174 Uncaught (in promise) Error: Boolean attributes can only contain a single expression
    at new BooleanAttributePart (idx-project-finder.js:2174)
    at DefaultTemplateProcessor.handleAttributeExpressions (idx-project-finder.js:2351)
    at _prepareInstance (idx-project-finder.js:1802)
    at TemplateInstance._clone (idx-project-finder.js:1815)
    at NodePart._commitTemplateResult (idx-project-finder.js:2109)
    at NodePart.commit (idx-project-finder.js:2052)
    at TemplateInstance.update (idx-project-finder.js:1761)
    at NodePart._commitTemplateResult (idx-project-finder.js:2110)
    at NodePart.commit (idx-project-finder.js:2052)
    at render (idx-project-finder.js:2452)
```

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by ruphin** [comment] 2019-02-09 17:03
I cannot reproduce the issue: https://codepen.io/ruphin/pen/dadLQX?editors=0010

Perhaps it is caused by the missing `'` after `ADVANCED`?

**Comment by justinfagnani** [comment] 2019-03-23 03:50
The problem here is the combination of
1. A self-closing tag
2. An unquoted attribute
3. The attribute being bound
4. The attribute being last, with no space before the `/`.

I'd just remove the `/`. It's not necessary in HTML.

**Closed by justinfagnani** 2019-03-23 03:50 UTC
Labels: Priority: Low, Status: Pending, Type: Bug

**Comment by idibidiart** [comment] 2019-09-08 18:01
Couldn't you just ignore the "/" part of the "/>" ? 

I got the error and was trying to figure out what the heck it means. Thankfully, Google does a good job of indexing github.

**Comment by jridgewell** [comment] 2019-09-08 18:24
More context in https://github.com/Polymer/lit-html/issues/905.

**Comment by idibidiart** [comment] 2019-09-08 18:38
@jridgewell 

That makes sense. Having said that, is there any way to detect "/>" and warn at design time? The way it is, it's impossible to tell what's going on from the error message, which I can understand is hard to disambiguate if the HTML parser is spitting out an error. 

A warning in a linter would help greatly. Is there a linter specific to lit-html or can we configure an existing linter? I've not used any linters (more trouble than worth it, unless I can set the rules from an empty slate) so I'm asking in general... thanks.

**Comment by LarsDenBakker** [comment] 2019-09-08 18:40
If it's invalid HTML https://github.com/43081j/eslint-plugin-lit#readme will catch it. Otherwise we should file an issue for them to detect this error.
