### ISSUE TITLE
Add zip file or bundle to releases

### ISSUE THREAD

**Issue by ThomasHickman** [Polymer/lit-html#961] opened 2019-07-11 13:03 UTC
It would be nice if the GitHub releases page contained some kind of compiled set (or single) file to easily download if you don't want to use cdns or npm.

**Comment by jridgewell** [comment] 2019-07-11 19:31
Closing this as a duplicate of https://github.com/Polymer/lit-html/issues/516. See https://github.com/Polymer/lit-html/issues/516#issuecomment-427239147 for the reasoning.

**Closed by jridgewell** 2019-07-11 19:31 UTC
