### ISSUE TITLE
template tag with on-handler attribute regex throws error

### ISSUE THREAD

**Issue by jimmont** [Polymer/lit-html#324] opened 2018-05-16 21:38 UTC
a template tag, when combined with the on-click handler, throws an error as detailed below

```
source excerpts:
import { LitElement, html } from '@polymer/lit-element/lit-element.js';
import { repeat } from '@polymer/lit-element/node_modules/lit-html/lib/repeat.js';


class ThisProblem extends LitElement{
	_render(){
		return html`
<template>
	${ repeat([{name:'asdf',title:'As Df'}], (i, index) => index, (i, index) => html`<span>${i.title}</span>`) }
</template>
<button class="menu-btn" title="Menu" on-click="${(e) => this._clickHandler(e)}">${this._name}</button>
`;
	}
then:
lit-html.js line 251 throws error:
// Find the attribute name
                    const attributeNameInPart = lastAttributeNameRegex.exec(stringForPart)[1];

error
lit-html.js:251 Uncaught TypeError: Cannot read property '1' of null
    at new Template (lit-html.js:251)
    at shady-render.js:29
    at render (lit-html.js:117)
    at render (shady-render.js:35)
    at HTMLElement._applyRender (lit-element.js:182)
    at HTMLElement._propertiesChanged (lit-element.js:132)
    at HTMLElement._flushProperties (properties-changed.js:335)
    at HTMLElement._flushProperties (lit-element.js:142)
    at HTMLElement.ready (properties-changed.js:179)
    at HTMLElement.ready (lit-element.js:70)

npm ls excerpt
─┬ @polymer/lit-element@0.5.1
│ ├── @polymer/polymer@3.0.2 deduped
│ └── lit-html@0.10.0
── @webcomponents/webcomponentsjs@2.0.0
```

**Comment by obedm503** [comment] 2018-05-16 21:49
are you using lit-extended?

**Comment by jimmont** [comment] 2018-05-16 22:36
@obedm503 yes I believe so, edited my first comment to add all of the relevant imports for clarity (specific versions are in the trailing part of the comment)

**Comment by jimmont** [comment] 2018-05-17 00:59
possible duplicate of https://github.com/Polymer/lit-element/issues/43

**Comment by smalluban** [comment] 2018-05-17 12:17
I think this because you put expression inside of the `<template>` element. `TreeWalker` used when a template is initialized is not traversing `template.content` DocumentFragment, so it does not find that dynamic part and breaks proper `index` of dynamic parts.

**Comment by smalluban** [comment] 2018-05-18 06:17
I am not sure what you want to achieve. Firstly, I would remove `<template>` wrapper from your iteration over an array inside of the repeat directive. As I wrote, expressions inside of the template element are not supported, and I really can't find any use case for that. Html method is what you should use to produce templates and let it use itself template element for you.

**Comment by jimmont** [comment] 2018-05-18 21:39
Thanks @smalluban is there an example of a sub-template anywhere? In the case of the above markup this is the excerpted implementation of vaadin components I'm using and don't know how to work around. Find more examples here: https://vaadin.com/components/vaadin-dropdown-menu/html-examples/dropdown-menu-basic-demos

If there is another way to write a lit- implementation of these examples please let me/us know how to get started and perhaps related detail when doing something that creates a conflict like this issue.

**Comment by justinfagnani** [comment] 2018-05-21 20:04
This is a dupe of #45. I'll get to that soon.

**Closed by justinfagnani** 2018-05-21 20:04 UTC
