### ISSUE TITLE
Property setter does not work if initial value is empty string

### ISSUE THREAD

**Issue by fineline** [Polymer/lit-html#872] opened 2019-03-19 10:13 UTC
I have prepared a repo which demonstrates the issue:

https://github.com/fineline/lit-html-set-property-bug

The README.md contains the full steps to quickly reproduce, as well as expected and actual behavior. Tested on Chrome 72 on OSX 10.14.

Essentially, it seems that a property setter like this:

`.value=${login.password}`

does not re-set the property when a new value of `login.password` is passed to the template UNLESS the initial value it was given on first render is a non-empty string.

I tried with a different input type to see if it was just passwords, but get the same behavior.

BTW lit-html is awesome, thanks.

**Comment by justinfagnani** [comment] 2019-03-19 21:08
I wasn't able to reproduce here: https://stackblitz.com/edit/lit-html-rt4n6e?file=src/index.js

There is an issue where user input into an `<input>` will not change the previously rendered lit-html value, so a programmatic update toa binding won't go. This is know and should probably be documented and we could offer a directive to work around it.

**Comment by fineline** [comment] 2019-03-20 04:41
Ah, OK, so I tried my example and set the initial value to "X" and tried to _reset_ the value to "X" in my auth() function and see the same thing. The value of `this.dirty` is false on line 403 of `parts.ts`. So yep as you say, to generalise it seems trying to change a user-entered value of an input back to whatever value lit-html previously rendered into that input doesn't work.

Yep it would be good to enable this by some means. My example provides one use case, where I don't want unencrypted passwords hanging around in the DOM or my application's model, even after an unsucessful login attempt. But I guess now I understand the limitation I can come up with a workaround. Thanks for your response.

**Comment by fineline** [comment] 2019-03-20 04:53
For now I can do a bit of a hack with an intermediate render with a random value to ensure that my actual update to the input value then succeeds. If you believe this could be resolved with a directive that would be great.

**Comment by fineline** [comment] 2019-03-20 04:58
And here's a fork of your stackblitz that demonstrates the behavior:

https://stackblitz.com/edit/lit-html-zmjftj?file=src/index.js

Change the value to anything other than "abc", click the button, and it is not reset.

**Comment by jridgewell** [comment] 2019-03-20 06:11
Directives actually enable this pretty easily, because the "dirty" value is set to the directive (really, to `noChange`). Then setting the desired value forces the reset:

```js
const forceWrite = directive((value) => (part) => {
  part.setValue(value);
});
```
https://stackblitz.com/edit/lit-html-o3j98s?file=src/index.js

**Comment by fineline** [comment] 2019-03-20 08:23
That's cool, thanks @jridgewell. Is there a good guide about directives anywhere? I have read about the built in ones but haven't found much info about making new ones.

**Comment by AStaroverov** [comment] 2019-03-20 10:18
I have same bug, and i think its incorrect behavior for this moment.

In line (file parts.ts)
``if (value !== noChange && (!isPrimitive(value) || value !== this.value)) {`` 

we check the change value with `!==` operator, but sometimes we override it with function `hasChange` and then we have unexpected behavior.

**Comment by justinfagnani** [comment] 2019-03-23 03:45
This was actually a dupe of #862, but I just opened a more general issue to cover both: #877. Let's discuss there.

**Closed by justinfagnani** 2019-03-23 03:45 UTC
