### ISSUE TITLE
Render svg sprite icon in template

### ISSUE THREAD

**Issue by marcuslindblom** [Polymer/lit-html#1071] opened 2020-01-21 06:14 UTC
Is it possible to render an svg sprite icon in a template using `html`?

This is what I try to achieve 
```js
    <ul class="commands">
      ${commands.map((command) => {
        return command.keyCode
          ? html`<li tabindex="-1" data-action="${command.action}" data-value="${command.value}">
              ${command.name}<span class="keycode">${command.keyCode}</span>
            </li>`
          : html`<li tabindex="-1" data-action="${command.action}" data-value="${command.value}">
              ${command.name}<span class="keycode"><svg class="feather"><use xlink:href="/static/sprite.svg#${command.icon}"/></svg></span>
            </li>`
      })}
    </ul>
```
but this section `<use xlink:href="/static/sprite.svg#${command.icon}"/>` does render the icon. But if I change to markup to `<use xlink:href="/static/sprite.svg#crop"/>` it works just fine? Am I missing something or is this just not possible?

**Comment by marcuslindblom** [comment] 2020-01-21 08:48
Found a solution [here](https://github.com/Polymer/lit-html/issues/423#issuecomment-432056517).

**Comment by justinfagnani** [comment] 2020-01-23 00:08
We're working on a fix to namespaced attributes, but can you just use the plain `href` attribute? It's supported in all browsers.

**Comment by justinfagnani** [comment] 2020-01-23 23:44
Closing as a duplicate of #423

**Closed by justinfagnani** 2020-01-23 23:44 UTC
