### ISSUE TITLE
Sometimes a child element is re-created in safari instead of just updating the attribute/property

### ISSUE THREAD

**Issue by pshihn** [Polymer/lit-html#575] opened 2018-10-18 20:56 UTC
This example is using lit-element but I think applies to lit-html as well:

https://jsbin.com/fereyax/edit?html,console,output

In this example, when the button is pressed the border style of a custom element is changed. The constructor of the child custom element `color-panel` logs a message in the console. 

This happens in various scenarios on iOS Safari, but most reliably reproduced as follows:
* Open the link https://jsbin.com/fereyax 
* click on the button to change the color
* Go to a different tab in Safari
* Come back to the original tab and click the button again
* At this point, the constructor of the child element is called again.

**Comment by pshihn** [comment] 2018-10-18 21:40
This happens on Desktop Safari as well if you go to a different tab and stay there for 30 seconds - 1 min. Go back to the tab and hit the button -> Child Element gets recreated.

**Comment by pshihn** [comment] 2018-10-18 21:44
I believe it has something to do with how Safari puts background tabs into hibernation.

**Comment by justinfagnani** [comment] 2018-10-18 22:13
This probably has to do with the template cache. We store the processed lit-html `Template` objects in a WeakMap keyed by the identity of the TemplateStringsArray that we received as the first argument. I bet that as a page hibernates, those objects are GC'ed, and when the page wakes up new instances are created, cause us to have cache misses.

**Comment by pshihn** [comment] 2018-10-18 22:19
I have reproduced this without switching tabs on mobile either, but it is much harder to reproduce. Even those scenarios could be explained where GC happens for whatever reason. 
(This bug is really annoying for one particular case I have, where the scroll position gets reset among other things in a virtual list).

**Comment by justinfagnani** [comment] 2018-10-18 22:37
We can use a Map instead of a WeakMap. It's a memory leak, but only of templates that are never rendered against and their source is collected correctly.

**Comment by ruphin** [comment] 2018-10-18 22:40
As I mentioned, I have no device that runs Safari. I'll try to get one next
week to run some tests.

**Comment by pshihn** [comment] 2018-10-18 22:47
> templates that are never rendered

Don't know the code well, but as an outsider: You could kep a WeakMap and a Map. Promote from WeakMap to Map on render.

**Comment by merlinnot** [comment] 2018-10-19 11:11
I have the exact same issue, it causes a lot of trouble especially with elements which are expected to be placed on a website at most once (e.g. dialog controller), containing Google Maps (resets positions, markers, overlays...) or having on-create animations (e.g. charts).

In my app there is no need to switch tabs, it happens every few seconds (there are some realtime updates).

**Comment by justinfagnani** [comment] 2018-10-19 17:12
@merlinnot are you also seeing the in just Safari?

**Comment by merlinnot** [comment] 2018-10-19 18:09
Yes, only in Safari. Chrome works perfectly fine.

**Comment by justinfagnani** [comment] 2018-10-19 18:10
Argh... I forgot that we hadn't actually switched to WeakMaps yet. This could be a nasty problem...

I made a JS-only reproduction and filed a WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=190756

**Comment by pshihn** [comment] 2018-10-19 18:33
Ugh! That means it may take some time till this is resolved. :(

**Comment by justinfagnani** [comment] 2018-10-19 18:45
I'm trying to ping my contacts on WebKit. We'll see. A workaround would be to either compile out template literals, or to concatenate the strings to build the cache key.

**Comment by justinfagnani** [comment] 2018-10-19 19:45
The bug is already imported to their internal system, so hopefully it gets addressed quickly. We'll still need a workaround in the meantime.

**Comment by ruphin** [comment] 2018-10-20 10:05
Here's a pure JS reproduction of the problem that @justinfagnani submitted to WebKit authors: https://codepen.io/pen/?editors=0012

What do you propose as a workaround until the fix for this lands? We could construct our own key from a string concatenation instead of using the array object id, but that means we can no longer use WeakMap to hold the templates, which adds a memory leak. It also has some other side-effects with template locality no longer being part of the key (i.e. two identical templates in different locations in the souce should have a different key under native implementation, but will share the same key with this implementation). I can't really think of another solution that does not have these problems.

Do you think we should use this workaround solution as a default for all browsers, or introduce some kind of detection for Safari and special-case for that browser only?

I'll try to have a preliminary PR in before end of the weekend that explores the available options.

**Comment by justinfagnani** [comment] 2018-10-23 01:46
For those following, @ruphin has a PR up at #579. With a small change, I think we can mitigate the perf impact to spec-compliant browsers and get this released soon.

**Comment by jyounce** [comment] 2018-10-23 09:34
I'm so glad someone else is experiencing this bug in Safari also (sorry for the enthusiasm). I have a couple key components that are broken in Safari because of this and have spent many hours trying to fix.

From what I have seen, it is like @pshihn explained "the constructor of the child element is called again". Which in turn causes Safari to loose the template.

To verify @ruphin solution PR #579, I updated template-factory.js with result.key and marker and it did seem to work. 

Please cut a release with this fix.
Much appreciated and great job on lit-html!

**Comment by justinfagnani** [comment] 2018-11-20 22:53
Fixed by #579

**Closed by justinfagnani** 2018-11-20 22:53 UTC
Labels: Priority: High, Status: Available, Type: Bug

**Comment by jyounce** [comment] 2018-12-05 06:41
Release v0.14.0 fixes the issue for me.
Awesome job and thanks a million!
