### ISSUE TITLE
Template Result injected into wrong part of dom

### ISSUE THREAD

**Issue by Toxyxer** [Polymer/lit-html#561] opened 2018-10-11 11:17 UTC
# Bug

When combined with custom elements, lit-html injects the template result into the wrong element on the page. Tested on Chrome 69.0.3497.100 and Firefox 63.0b13 Windows 10 64-bit.

## Steps to replicate:
[repo](https://github.com/Toxyxer/invalid-dom-injection)
```
npm i
npm start
```
Open file dist/index.html in a browser supporting custom elements.

**Comment by justinfagnani** [comment] 2018-10-11 13:44
Where is the template rendered?

**Comment by ruphin** [comment] 2018-10-11 13:52
I'm looking into this issue at the moment

**Comment by ruphin** [comment] 2018-10-11 14:33
I found the problem. This example modified the LightDOM in the constructor of a custom element. This is forbidden by the Custom Element specification, so this is not necessarily an issue. However, simple elements that modify their LightDOM in the constructor can technically exist, and when you use such an element inside a template, it throws off the ability of lit-html to parse the template.

Here is a minimal example:
https://codepen.io/ruphin/pen/oawzNG?editors=1010

The example works fine when we modify the invalid element to render in the `connectedCallback` instead.

Do we want to modify lit-html to detect this problem somehow, or simply ignore it and point to the Custom Elements spec?

**Comment by Toxyxer** [comment] 2018-10-11 17:21
Didn't realize it's forbidden. In that case, I don't think it should be addressed in lit-html.

**Comment by abraham** [comment] 2018-10-11 18:17
It would probably save a lot on future support issues to not that limitation in the documentation.

**Comment by justinfagnani** [comment] 2018-10-11 18:45
@abraham not sure where. lit-html docs don't really reference Web Components concepts, though we can add links to webcomponents.org or MDN.

**Comment by abraham** [comment] 2018-10-11 19:03
@justinfagnani I would put it right on [lib/render](https://polymer.github.io/lit-html/api/modules/_lib_render_.html). I would think a substantial amount of lit usage will be in web components. Or wait until the next support request.

**Comment by Toxyxer** [comment] 2018-10-12 11:46
If it's forbidden too, then ignore this, but I noticed that this also happens when modifying lightDOM via attributeChangedCallback. I've updated the [repo](https://github.com/Toxyxer/invalid-dom-injection) and [here](https://codepen.io/anon/pen/mzMPRN?editors=1010) is the codepen version.

**Comment by ruphin** [comment] 2018-10-12 12:36
AttributeChangedCallback is called before the element is connected, so it's still somewhat weird, but it isn't explicitly disallowed. It is certainly a gray area, but it seems to me like lit-html should be able to handle this case. It might be some regression in the template handling, causing elements to upgrade too soon. I will look into it. Thanks for the report @Toxyxer

**Comment by ruphin** [comment] 2018-10-14 22:36
This might be a serious issue.

According to the [Web Component specification](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements) the limitation of not accessing the children or attributes [only applies to the constructor](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance). Technically, making changes to the children of a Custom Element in the `attributeChangedCallback` is allowed, although the spec is not explicitly clear on this. Regardless of whether it is allowed or not, there is a chance users will do this by accident, and it will break lit-html.

Currently we default to using `importNode` when cloning templates: https://github.com/Polymer/lit-html/blob/d2be7ca48780120be3a66101e0db6a034592c002/src/lib/template-instance.ts#L62-L64

The reasoning behind the clause was that CustomElements should technically not modify their innerHTML before the connectedCallback is called. We had to make an exception for when the Custom Elements polyfill was used, because that is more likely to modify LightDOM when combined with the ShadyDOM polyfills.

Here's a simple reproduction that shows `attributeChangedCallback` is in fact called when `importNode` is used: https://codepen.io/ruphin/pen/mzBzOa?editors=1010

Considering this, I think we may have to also use `cloneNode` with native Custom Elements. Downside is that template cloning may be slightly less efficient when we clone and adopt the fragment in separatele calls. Upsides are that we fix this issue, and lose a special case for polyfills. What do you think @justinfagnani ?

I can make a PR that implements this change and adds a test case with a Custom Element that contains this behaviour, to avoid regression.

**Comment by ruphin** [comment] 2018-10-14 23:00
This test shows that the `attributeChangedCallback` has the same behaviour as the `constructor` with regards to the child content not being accessible.

https://codepen.io/ruphin/pen/dgVgJq?editors=1010

It could be that the intended behaviour of the spec is that the `attributeChangedCallback` should have the same restriction as the `constructor` with regards to accessing child content.

I will raise an issue in with the spec to clarify. If the outcome is that `attributeChangedCallback` is indeed not allowed access, then we are spec compliant, which may change decision process on this issue.

**Comment by ruphin** [comment] 2018-10-14 23:34
https://github.com/w3c/webcomponents/issues/767

**Comment by ruphin** [comment] 2018-10-15 19:02
Well, we got confirmation from the webcomponents spec authors that it is fine spec-wise to manipulate LightDOM in the `attributeChangedCallback`. This means that our current approach of upgrading elements before parsing the tree to find parts is not viable, because upgrading elements may cause `attributeChangedCallback` to fire, which in turn may modify the DOM, which breaks our code.

I will make a PR that fixes this. Thanks again @Toxyxer for bringing this issue to our attention.

**Comment by justinfagnani** [comment] 2018-10-15 19:08
@ruphin I'm not sure we want to incur the extra tree-walks involved in adoptNode and upgrade without making sure it doesn't impact perf too much.

**Comment by ruphin** [comment] 2018-10-15 19:11
There should be no additional tree walking compared to previous implementation. The only difference is that we defer upgrading elements until after we walk the tree. Can you clarify how this would lead to extra tree-walks?

**Comment by ruphin** [comment] 2018-10-15 19:12
I will prepare a jsperf test on this to check if there is a significant difference.

**Comment by justinfagnani** [comment] 2018-10-15 20:34
Right now we have either 3 or 5 tree walks:

Native Custom Elements:
1. Import template (native)
2. Prepare template (JS)
3. Append fragment (native)

Polyfilled Custom Elements:
1. Clone template (native)
2. Prepare template (JS)
3. Adopte fragment (native)
4. Upgrade fragment (native)
5. Append fragment (native)

Changing to use the same approach for each would add 2 native tree walks for the native case. It could be that native tree walks are fast enough that they don't show up, or only show up in micro-benchmarks and not in application code. That would be ideal, as it's the more correct ordering that can handle all sorts of ill-behaved components.

**Comment by ruphin** [comment] 2018-10-15 21:18
It's true that we need a separate cloning and adoption phase compared to the original single import, but I assume that the adoption tree walk also handles the upgrades without requiring an additional tree walk, similar to the import tree walk.

I think these native tree walks should be efficient enough, but to make sure I will prepare some kind of benchmark to test this.

**Comment by justinfagnani** [comment] 2018-10-15 21:27
afaik, this is the correct steps in the correct order. Remember that in between upgrade and append we set properties, so we can't use append to drive the upgrade.

**Comment by ruphin** [comment] 2018-10-15 22:03
I was hoping that there was a way to adopt the cloned template and upgrade at the same time, but this seems to be impossible. `importNode` will immediately upgrade because the clone routine is passed the right context, which causes synchronous upgrades of custom elements during the cloning process.

We'll have to wait for the result of the benchmarks. It would be very unfortunate if it causes a significant slowdown, since that would mean we will have to choose between performance and spec compliance.

**Comment by justinfagnani** [comment] 2018-11-30 00:50
We're going to investigate this issue more after 1.0. Right now we advise that elements don't change their own light-dom (that's what ShadowRoots are for), but if you do, don't add light-DOM children until `connectedCallback()`.

Later we'll see if not upgrading template instances until after template processing is acceptable perf-wise.

**Closed** 2019-02-27 21:14 UTC
Labels: Priority: Medium, Status: Available, Type: Bug
