### ISSUE TITLE
Zero length string not recognised as changed, so previous content not removed.

### ISSUE THREAD

**Issue by akc42** [Polymer/lit-html#606] opened 2018-11-02 17:05 UTC
I have a small bit of logic related to a boolean variable which controls whether or not some dom displays or not.  During the initialisation phase the `render` function notices this boolean variable as false and displays (correctly) nothing.  A bit later this variable is set to true and the `render` function then shows the content.  Later still the boolean variable is set back to false, but then the `render` function does not remove the old content.

Here is a snippet from a test I set up to show this - the controlling property is `this.active`
```
  render() {
        return html`
          <style>
            :host {
              display: block;
            }
            .textblock {
              cursor: pointer;
            }
          </style>
          ${this.active?  when(this.showForm,() => html`
            <div class="testblock" @click=${this._showResults}>Form Showing, click to switch to results</div>
          ` , () => html`
            <div class="testblock" @click=${this._close}>Results showing click to close</div>
          `): ''}
        `;

``` 

There is a complete repository at  https://github.com/akc42/test-lit.git

I've done a bit of digging with the debugger, and what I think is happening is that the template is switching between having a "primitive" node part and a "templateResult" part.  When it returns to the "primitive" part the old value of "" remains (its is never set to `noChange`) so hasn't apparently changed and so nothing is done to the render.

**Comment by akc42** [comment] 2018-11-02 17:41
Actually I think the problem is with using `when` directive when its not embedded in a `html` tagged string. If I change it to the following the problem goes away:-
```
      render() {
        return html`
          <style>
            :host {
              display: block;
            }
            .textblock {
              cursor: pointer;
            }
          </style>
          ${this.active?  html`${when(this.showForm,() => html`
            <div class="testblock" @click=${this._showResults}>Form Showing, click to switch to results</div>
          ` , () => html`
            <div class="testblock" @click=${this._close}>Results showing click to close</div>
          `)}`: ''}
        `;
      }
```
Or even simpler lose the `when` directive altogether:-
```
      render() {
        return html`
          <style>
            :host {
              display: block;
            }
            .textblock {
              cursor: pointer;
            }
          </style>
          ${this.active?  this.showForm? html`
            <div class="testblock" @click=${this._showResults}>Form Showing, click to switch to results</div>
          ` : html`
            <div class="testblock" @click=${this._close}>Results showing click to close</div>
          `: ''}
        `;
      }
```
And again the problem disappears.

Is this a limitation of all directives?   If so it needs documenting I am using directives like this in quite a few places

**Comment by mariusGundersen** [comment] 2018-11-03 12:31
This is a bug caused by the when directive not setting the value of the parent part, so the value stored in the part doesn't change from when `this.active` was false. This is a general problem with directives as they currently work.

Here is a simple test-case for this scenario:

```js
render(html`${false ? when(true, () => 'OK', () => null) : ''}`, container);
render(html`${true ? when(true, () => 'OK', () => null) : ''}`, container);
render(html`${true ? when(true, () => 'OK', () => null) : ''}`, container);
```

In the first render `part.value` is set to the empty string (`''`), in the second case a directive is discovered so the value isn't set by the part, therefore the previous value sticks around. That means that when the third render is called it compares the new value with the old, and they are the same, so it decides not do anything.

I wanted to see if this was only a scenario for the empty string or not, and ran this scenario:

```js
render(html`${false ? when(true, () => 'OK', () => null) : 'NO'}`, container); // outputs NO
render(html`${true ? when(true, () => 'OK', () => null) : 'NO'}`, container); // outputs NOOK
render(html`${true ? when(true, () => 'OK', () => null) : 'NO'}`, container); // outputs NOOK
```

Since the `when` directive assumes the part is empty when it first renders it does not clear away whatever is there already, so the result is both the true and false case at the same time.

**Comment by LarsDenBakker** [comment] 2018-11-03 12:32
It's an easy fix, but currently on hold given the discussion around the cache directive.

**Comment by justinfagnani** [comment] 2018-11-21 19:29
Right now, directives are fragile when used inside conditionals, or when composed. This has been discussed in some other issues. One solution we sketched out ended up being very similar to how React tracks state for hooks, but it'll have the same limitations (no conditionals). We had thought that was a bad constraint, but it seems ok in the React world.

Going to close this in favor of a more general issue around directives.

**Closed by justinfagnani** 2018-11-21 19:29 UTC
