### ISSUE TITLE
Discussion: use semantic-release and conventional commits

### ISSUE THREAD

**Issue by web-padawan** [Polymer/lit-html#929] opened 2019-05-23 07:22 UTC
# Description

Let me ask your opinion about using [semantic release](https://github.com/semantic-release/semantic-release) or similar tool to improve the workflow so that new versions are released in CI, based on [conventional commits](https://www.conventionalcommits.org/en/) specification.

How is this helpful:

1. No more accident mistakes with releases, like 1.1.0 instead of 1.0.1 https://github.com/Polymer/lit-html/pull/921#issuecomment-494864271

2. Bug fixes / new features are delivered immediately after they are merged to master. After 1.0.0 there has been a number of commits waiting to be released for a while.

3. Granular releases making it easier for consumers to investigate (with no need to git bisect), in case some change in the library breaks their own code / tests.

**Comment by kevinpschaaf** [comment] 2019-05-28 22:18
One consideration: As part of our release process, we typically block external release on internal Google tests passing, which we think think provides value externally given that Google writes a _lot_ of tests (we can effectively test a change we _think_ should be semver-non-breaking release against thousands of real-world use cases on a pass/fail basis, far more than we could ever write in the library's own unit tests).  However, there are technical and security-related challenges to integrating the external CI with our internal systems.

**Comment by justinfagnani** [comment] 2019-06-14 18:05
I would be open to publishing a pre-release tag automatically, and doing releases PRs _more_ automatically.

**Comment by ruphin** [comment] 2019-06-14 19:02
I think not releasing often is a feature, not a bug. Lit-html is quite fragile in the sense that applications stop working if for any reason multiple versions of lit-html exist. Because NPM does not really having any features to systematically avoid this, the more often we get new releases the more often things will break.

Also, packages that depend on some kind of pre-release version will be incompatible with packages that depend on a non-pre-release version, by definition. I think it's a terrible idea to have two "official" releases that are incompatible with eachother, it will just lead to fragmentation of the ecosystem.

**Comment by justinfagnani** [comment] 2019-06-14 19:32
Packages should definitely not depend on a pre-release version, but if people want to check out upcoming bug fixes and perf improvements, they could..

**Comment by ruphin** [comment] 2019-06-15 11:16
Checking out what is the latest state of the library is already possible by installing from the master branch on github. Installing packages off a git repo is supported in NPM, but unlike a different package version it is very clear that it is something you should probably never do in a published package.

**Comment by justinfagnani** [comment] 2020-04-02 19:10
We've decided to not do automatic releases in order to keep a final safety check before publishing new features that might have had unexpected costs that we discover after merging. This happened recently with some security changes. Given that we can't unrelease a feature, we'd be in a tough spot if we automatically released something and regretted it later.

Adopting tooling to automate the release process more may be helpful, though we'd still need manual editing for cases where we both added and removed a feature in between releases.

**Closed by justinfagnani** 2020-04-02 19:10 UTC
Labels: Needs Discussion, Severity: Medium
