### ISSUE TITLE
Value updates not rendering

### ISSUE THREAD

**Issue by CaptainCodeman** [Polymer/lit-html#379] opened 2018-06-24 23:07 UTC
I've noticed a few issues since the last update where values and/or updates to them aren't rendered. I've managed to create a cut-down example to demonstrate the issue:

This is using v0.10.0
http://jsbin.com/fadogipafi/1/edit?html,output

Click the add button a few times and you should see the items all with the same values repeated in the row as I expect it to work:

<img width="199" alt="screen shot 2018-06-24 at 4 56 20 pm" src="https://user-images.githubusercontent.com/304910/41824599-26016c08-77d0-11e8-9023-7a85427489f8.png">

Now try the same thing with v0.10.2
http://jsbin.com/moboqobiba/edit?html,output

This time some of the values stop rendering and are inconsistent, even though they should all be referencing the same value:

<img width="206" alt="screen shot 2018-06-24 at 4 56 48 pm" src="https://user-images.githubusercontent.com/304910/41824614-57f76578-77d0-11e8-8429-d7f187aca726.png">

In a more complex app I'm seeing this manifest itself in strange random ways such as some cart-items or the cart total not updating and every time I've confirmed that the values are correct and if I output them in the template instead of passing them into a child element they show up correctly. In some cases, a repeat directive list will render correctly but the same items output with a map won't. When it happens, it's like the property setter is never being called at all.

**Comment by bgotink** [comment] 2018-06-25 23:21
This is caused by #241:

- The template is stamped, but the cloned content is not yet adopted by the document (so custom elements are not upgraded yet, which is what #241 was all about)
- The initial values are set
- The clone is inserted into the document, it gets adopted which leads to the custom elements getting upgraded.

This means that in the constructor of the `MyItem` in the example, `this.item` can already be assigned to a value. This is similar to what went wrong in https://github.com/Polymer/lit-html/issues/237#issuecomment-355672630.

Fixing this should be as easy as moving line 182 to the bottom of the render function ([working jsbin with the patch](http://jsbin.com/ladiyecoqa/edit?html,output))

https://github.com/Polymer/lit-html/blob/0cde2220c1beb43ce4adcf5c21d01a6ab1507e92/src/lit-html.ts#L181-L185

**Comment by CaptainCodeman** [comment] 2018-06-26 01:57
I can confirm that also appears to fix it in the app as well - thanks for the detailed explanation 👍

**Closed** 2018-06-26 22:53 UTC
Labels: Priority: Critical, Status: Accepted, Type: Bug
